language: node_js
node_js:
- 11.14.0
cache: yarn
before_install:
- if [[ -n "$encrypted_5b7b89e871be_key" ]]; then openssl aes-256-cbc -K $encrypted_5b7b89e871be_key
  -iv $encrypted_5b7b89e871be_iv -in .travis/.service-account-key.json.enc -out .service-account-key.json
  -d; fi
  # install specific version of yarn
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
- export PATH="$HOME/.yarn/bin:$PATH"
- echo $import_ui_data_pwd | gpg --passphrase-fd 0 .travis/serviceAccountKey_tests.json.gpg
- mv .travis/serviceAccountKey_tests.json cypress/support/serviceAccountKey.json
script:
#- node cypress/support/import-ui-test-data-to-firestore.js 
#- yarn test-with-coverage
#- yarn test-no-cycles
#- yarn lint
- cp .travis/.env.feature-tests ./.env.local
- yarn start &
- yarn wait-on http://localhost:3000
- yarn cypress run --record
# .env.production is kept out of the root directory, because if it were there
# running "firebase deploy" would create a clone of our real production
# environment. This is not something we can stop (they are public details) but
# we should at least stop people from doing it accidentally.
- cp .travis/.env.production ./
- yarn build
after_success:
- yarn upload-coverage-report
branches:
  only:
  - master
deploy:
  provider: firebase
  project: boxwise-production
  edge: true
  skip_cleanup: true
  token:
    secure: tMSjTph1dH/aU8XkrxpyjT5b911oi7+qIylFySz81u17eNVb7jtmtsNz8SuGZW0u+U+1E6hK9AeotwvTAbKpRtDZYi8lZ4sgcswVkMdk8wHsyTN1kJdatkUV9msi5DMYasHVMTUGTwhICtO4wVoEZ2KuxuwC6kaAXSq6s9nQdb/LJcArzhOYbYQAnSIW4uouPmjrGmF/kxcVrtnfYHTL48Dru7bi7t4ukdhxFNnr6oVX5LUa6O35KMtLEQRpP/0jYAzPPMMPVjVCIsTe96qXkUDY9r2B24CAxYQOwCUMw0lsWJca2pVxkJNgedMOHPH91z1qv9KG+eJSR7O7dGS4cj0EYMF4t3rXjiEEwKcK0G4hYZKGCgsXTAv+RQup/NmkKdtEB7Xtzut7a1oh85rSCPS2hzefOj/2GzS2tRgtyECb1b+tfHB6Pko/eRHqaiH+SGR7iKn96TAp0MxAeJ0v1blY+FzRfNH/LM0BpXtcb5jkNMX5S+HrFuD6yexqK41Q6+5utH8SRBVaVUVccNQ2R0CSK9gloTzRvopu8ITpZkGvisYRB93JeoE4T/UX7E58wwU1CxT1eHUiQI97X3gTO59ZeuWsvkShUsUGLKCdZZXy01eZ+eYHLBSoo7NTU6cwjz7VmJFpLyLP56wQa7+nWXlrY1gAuL+IsVklzY9GVYg=
notifications:
  slack:
    on_success: change
    on_failure: change
    rooms:
      secure: UsyAyS/TPGo5n4t7xaasx13IQkJPREUliDee4N5UaDaj1rZ9qUkRhcQaVuouSbM+8l5fN04l2aNeVJQeX9aODaQ2sGKeNdhtXknI+ivUrJonmsuXbnntU+/XYTBDUE57vz0CCIY2/HjXMnrz5NuXkb88r2bvzhtphACqeFrgqlZ0RxghKAdpUWadQhAm56C9ibNfOWSuC8HqCPhixJXpJlOmRoJ9ZcjOUy+8c6EEdxvMqH/Jv4dCqVQTYdJdo1ymME/1euN52/a2igS43sPug5KJh0Gnm1SrAvEPgBUH4gMWvaew8wt6WHPkTN2vcDphkz5KguH2DYZJ0reBItOSawAUlY8Md7CUlDQ+fWN77piZShKMye8NSWnGOK6lr7gWIYAeUt3dtxkszY5YFdPh8OfwAPeRmGLRsHg4TTeyVFuhG2vIpOapF2usVcpTzGZTKaz7VMS0yyVI5vt2NOj8p4tAJpXpVmQQw1MspLVI3nkgfw0XV/btjZxoMzIK0YoMWWTH42VVxVwiPz63+sUSiAU0XbDWY01G90w20Qtzj3ui6DiiwMrJ+Zf0Ym/ltv04IQjYxwyxuHoVY4AYA8zLaMZf8+gkcWkvKqBSfs062CMxTXFnyrid3D9jbZXOqrZ5+Dsz0lUF9AP4sQ6XEQ+OtWFiQYpzp34jzadPYLYPJco=
env:
  global:
    secure: QYIvngh04PZzLQNGXq2DHKYUQ+6tYKzS6Sx4mt16jbih7Xuj9wUdByzii/7i2D060AQrv45EqwwH2D8+DLbgdOcqxgcl4HAwLOqf3VeyrtnOBiDDLj6JATQj7Vyzso6FuBR6NBVY4SQDUyLqUBXz1UJDmFWturCr/WGYT1JpJQDxGWD3scgzGctpN5jPBl01W2QpJ1U8EheYVRfm1/X64EYInDqXQkAXOI6CI/107f6X2D3gtBpAJu66k6x3KqT79wtqR68PgrlQnP2c5HQYwDVeBIF8eDQrkCrgtHiUyU13Iyr82hNi9QpuxSeYo0oHVPbujv3F/RRJUz4twUPcBSvAV1rUx3ucmRD4k951ZzvtTxF7CMKF6XuWXVkcAdd9fc4fOgEBGMbODaK+lEaDM+ctTmdIuc5SXkKmAW3SRmWTg0DDdO5KMoWlV0ANHLy+b9G70OoreSoVWPn07syNiKGvwsc2INCjMlnHCn5mVfVUXktqctX45Nl4HD7OUDjWfDtyeS8zrclmQ0mSv06mtL9UPMhFu0e6M+qcw4pUR/alHfrryPzBoBddQFQkTqqTpzRJfmL0McRe7KZruH7VKNfDi4FY6B39mQmZgLqRIysnwSFibqZzRQ15Y36VSWRZzsggt4Mzer9YCYEDg8ruI9MhB1K6rGWOcznyPWgUHrU=
